language: php

php:
  - 5.5
  - 5.6
  - hhvm

sudo: false

env:
  - APPLICATION_ENV=testing

before_install:
  - composer self-update

install:
  - composer install
  - php -r "copy('app/config/config.example.php', 'app/config/config.php');"

script:
  - phpunit
